package graph.cfg.analyzer;

import java.util.List;

import graph.cfg.IFlowInfoRecorder;

/**
 * @author Zhou Xiaocong
 * @since 2017Äê9ÔÂ10ÈÕ
 * @version 1.0
 *
 */
public interface IReachNameRecorder extends IFlowInfoRecorder {

	/**
	 * Add a generated name definition and its value (reference).
	 * Note: a generated name definition in a node also kills all name definition defined in the precede nodes 
	 */
	public void addGeneratedName(ReachNameDefinition definedName);

	/**
	 * Add a defined name definition to the current node. All added defined names can reach this node. 
	 * In fact, those defined names include generated name definition in this node and all defined names
	 * which reach the precede nodes and not generated (also killed) by this node. 
	 */
	public boolean addReachName(ReachNameDefinition definedName);
	
	/**
	 * Get all defined names reach this node
	 */
	public List<ReachNameDefinition> getReachNameList();
	
	/**
	 * Get all defined names generated by this node
	 * Note: we can also get all killed names by this node from its generated names
	 */
	public List<ReachNameDefinition> getGeneratedNameList();

}
